### ISSUE TITLE
[Discussion] Using create-playwright on macOS 10.13

### ISSUE THREAD

**Issue by dotnetCarpenter** [microsoft/create-playwright#74]
Hi all.

I'm arguably on an old system but can not upgrade to a later macOS.

Because the latest supported OS on this hardware is **macOS 10.13.6 High Sierra**, I'm currently fixed on the following versions (+ indicates I'm able to use the latest version and can probably continue to upgrade for a while):

1. nodejs: `16.x` (npm 8.19.3)
2. Corepack: `0.15.1`
3. Firefox: `108+`
4. Chromium: `109+`
5. AppleWebKit: `605.1.15`

There is already a closed PR, https://github.com/microsoft/playwright/issues/1941#issuecomment-1008338376, with a work-around for `npm init playwright@latest` failing on macOS 10.13.

I would like to contribute to a better Developer eXperience (DX) for us on old Apple hardware, if possible.

Below is my notes for getting Playwright to work on 10.13. Any of the sections could be turned into a PR, if desired by you. I don't see any guidelines for what is supported other than comments [here](https://github.com/microsoft/playwright/issues/1941#issuecomment-651363301) and [there](https://github.com/microsoft/playwright/issues/1535#issuecomment-604347169).

## Steps to reproduce

`npm init playwright@latest`

## Result

```
Error: ERROR: Playwright does not support webkit on mac10.13
Error: Command failed: npx playwright install
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at executeCommands (/Volumes/mystuff/dotnet/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/Volumes/mystuff/dotnet/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4660:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Volumes/mystuff/dotnet/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4928:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2004,
  stdout: null,
  stderr: null
}
```

## Steps to reproduce

`npm i && npm test`

## Result

All of the tests fails.

```
1) [NPM] › integration.spec.ts:20:1 › should generate a project in the current directory =========

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      21 |   test.slow();
      22 |   const { exitCode, dir, stdout } = await run([], { installGitHubActions: true, testDir: 'tests', language: 'TypeScript', installPlaywrightDependencies: false, installPlaywrightBrowsers: true });
    > 23 |   expect(exitCode).toBe(0);
```
_The same error happens in all of the tests._

## Possible solution

Since the test output does not say what why all of the tests failed, I added a `stderr` property to `type RunResult` and in _integration.spec.ts_ I print to `console.error` if `exitCode` is not above 0.

I could then see that the tests expects `yarn` and `pnpm` to be globally installed. I don't know if it makes sense to add package managers to the `devDependencies` for create-playwright but I'm assuming it does not.

A fix could be to just write that `npm`, `yarn` and `pnpm` is required for the tests to run, in the _[README]_.
After installing `yarn` 2 and still failing all tests, I took a peek at what the macOS github action is using and it turns out to be `yarn@1`. This should also be clear in the _[README]_.

The steps required, according to _.github/workflows/.ci.yml_, are the following:

1. `npm i -g npm@8`
1. `npm i -g yarn@1`
1. `npm i -g pnpm@7`
1. `npm ci`
1. `npx playwright install-deps`
1. `npm run build`
1. `npx tsc --noEmit`
1. `npm test`

Despite successfully doing the above steps, all of the tests still fails. Fortunately, with the `stderr` property, I am now able to see which commands fails.
The first one being, `npx playwright install`, which brings be back to my original issue, _"Playwright does not support webkit on mac10.13"_.

Running the test with `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true npm test` gives the same errors.

It seems that I can not get any further without looking into the source of microsoft/playwright...
I will update this issue with my findings :)

Related issues:
+ [1535]
+ [1941]

[README]: https://github.com/microsoft/create-playwright/blob/738f603c12ee7ba9e710e7a3bbab94dd99e4ad1c/README.md
[1941]: https://github.com/microsoft/playwright/issues/1941
[1535]: https://github.com/microsoft/playwright/issues/1535

**Comment by dotnetCarpenter** [comment]
Right, after looking through the source in [_playwright_][playwright], I see that a lot of things has changed since the before mentioned issues - I simply can not find out where add logic for which browsers to download by default.

I think it is somewhere in [playwright/packages/playwright-core/src/server/registry/index.ts](https://github.com/microsoft/playwright/blob/359d176ff6e4b2d8da953e459ab540b3b5e8a7ab/packages/playwright-core/src/server/registry/index.ts). Preferably it should not be logic somewhere in the belly of [playwright] but flags/arguments to playwright CLI with logic in [create-playwright].

[playwright]: https://github.com/microsoft/playwright/
[create-playwright]: https://github.com/microsoft/create-playwright/

**Comment by mxschmitt** [comment]
Supporting macOS 10.15 or lower is unfortunately out of scope, since e.g. WebKit does not support them anymore due to their minimal xcode version constrains.

macOS 10.15 does no longer receive security updates by Apple as well, so we recommend updating.

Closing since this is not actionable for us.

**Comment by dotnetCarpenter** [comment]
I can not update. I would have to throw out my hardware and buy new... I understand that Microsoft don't want to support outdated OS's but the community could support macOS 10.13+. The latest webkit for iOS 15.7.2 (webkit 605.1.15), is also supported on 10.13 - I am running Safari 13.1.2 AppleWebKit/605.1.15.

> WebKit does not support them anymore due to their minimal xcode version constrains.

@mxschmitt how does the xcode version come into play with [playwright]? I see [relative download paths to a _builds/_ directory](https://github.com/microsoft/playwright/blob/359d176ff6e4b2d8da953e459ab540b3b5e8a7ab/packages/playwright-core/src/server/registry/index.ts#L188) but fail to get a sample of the corresponding _.zip_ file.

![Screen Shot 2023-01-04 at 10 24 32 (2)](https://user-images.githubusercontent.com/43763/210524056-9df722d0-d071-49cd-832f-686d95aa6b5f.png)


[playwright]: https://github.com/microsoft/playwright/

**Comment by dotnetCarpenter** [comment]
Also, it strikes me that playwright is also very useful on macoS 10.13 for Chromium and FIrefox browsers, which runs just fine.

**Comment by dotnetCarpenter** [comment]
Alternative if playwright does not run on old hardware, then there is only [karma](https://github.com/karma-runner/karma) and [puppeteer](https://github.com/puppeteer/puppeteer) - though I can not find supported OS's in Puppeteer's documentation.

@mxschmitt can you confirm that cross-platform testing (for developer machines) would be possible with Docker?

**Comment by dotnetCarpenter** [comment]
>The latest WebKit version is 16.2, which is much more recent than yours, see [here](https://developer.apple.com/safari/resources/). 605.1.15 is not the version number.

@mxschmitt that's not strictly true. The version numbers can be found here: https://github.com/WebKit/WebKit/blob/main/Configurations/Version.xcconfig

But you're correct that my webkit version is not the latest. It is however, the latest on iOS 15.7 which is still supported by Apple.

Again, I fail to see why you impose this requirement to playwright? Is it because you do not have old macOS's to test on? Is it because playwright depends on a specific xcode version - if yes, where and how?

Sorry about all this questions - but I'm very confused to why playwright would not work on macOS 10.13-10.15.

Previously (in August 2022) _Version.xcconfig_ was here: https://trac.webkit.org/browser/trunk/Source/WebCore/Configurations/Version.xcconfig

Versions were unified in these two PR's: https://bugs.webkit.org/show_bug.cgi?id=244450 (https://github.com/WebKit/WebKit/pull/3747) and https://bugs.webkit.org/show_bug.cgi?id=249718 (https://github.com/WebKit/WebKit/pull/7958).
